// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/signup",
				Handler: UserRegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1",
					Handler: LatexGenerateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/download",
					Handler: pdfHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/pic",
					Handler: uploadPicHandler(serverCtx),
				},
			}...,
		),
	)
}
