// Code generated by goctl. DO NOT EDIT.
package types

type PdfRequest struct {
}

type PdfReply struct {
	ResponseData Reply `json:"code"`
}

type LatexGenerateRequest struct {
	T1  string `json:"t1"`
	T2  string `json:"t2"`
	T3  string `json:"t3"`
	T4  string `json:"t4"`
	T5  string `json:"t5"`
	T6  string `json:"t6"`
	T7  string `json:"t7"`
	T8  string `json:"t8"`
	T9  string `json:"t9"`
	T10 string `json:"t10"`
	T11 string `json:"t11"`
	T12 string `json:"t12"`
	T13 string `json:"t13"`
	T14 string `json:"t14"`
	T15 string `json:"t15"`
	T16 string `json:"t16"`
	T17 string `json:"t17"`
	T18 string `json:"t18"`
	T19 string `json:"t19"`
	T20 string `json:"t20"`
}

type LatexGenerateReply struct {
	ResponseData Reply  `json:"code"`
	Filename     string `json:"downpath"`
}

type Reply struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type LoginRequest struct {
	Name     string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	ResponseData Reply  `json:"code"`
	Token        string `json:"token"`
}

type UserRegiserRequest struct {
	Name       string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"confirm_password"`
}

type UserRegiserReply struct {
	ResponseData Reply `json:"responseData"`
}
