// Code generated by goctl. DO NOT EDIT.
package types

type PdfRequest struct {
}

type PdfReply struct {
	ResponseData Reply `json:"code"`
}

type LatexGenerateRequest struct {
	Content string `json:"content"`
}

type Content struct {
	Type        string   `json:"type"`
	TextContent []string `json:"textContent"`
}

type LatexGenerateReply struct {
	ResponseData Reply  `json:"code"`
	Filename     string `json:"downpath"`
}

type Reply struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type LoginRequest struct {
	Name     string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	ResponseData Reply  `json:"code"`
	Token        string `json:"token"`
}

type UserRegiserRequest struct {
	Name       string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"confirm_password"`
}

type UserRegiserReply struct {
	ResponseData Reply `json:"responseData"`
}
