// Code generated by goctl. DO NOT EDIT.
package types

type PdfRequest struct {
}

type PdfReply struct {
	ResponseData Reply `json:"code"`
}

type LatexGenerateRequest struct {
	Title            string     `json:"title"`
	Subject          string     `json:"subject"`
	GroupLeaderName  string     `json:"groupLeaderName"`
	GroupMemberName  string     `json:"groupMemberName"`
	Classes          string     `json:"classes"`
	Teacher          string     `json:"teacher"`
	Company          string     `json:"company"`
	LeaderWorkDivide []*Content `json:"leaderWorkDivide"`
	MemberWorkDivide []*Content `json:"memberWorkDivide"`
	Requirement      []*Content `json:"requirement"`
	DemandAnalysis   []*Content `json:"demandAnalysis"`
	OutlineDesign    []*Content `json:"outlineDesign"`
	SourceCode       []*Content `json:"sourceCode"`
	TestAndResult    []*Content `json:"testAndResult"`
	Question         []*Content `json:"question"`
	Summary          []*Content `json:"summary"`
}

type Content struct {
	Type        string   `json:"type"`
	TextContent []string `json:"textContent"`
}

type LatexGenerateReply struct {
	ResponseData Reply  `json:"code"`
	Filename     string `json:"downpath"`
}

type Reply struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type LoginRequest struct {
	Name     string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	ResponseData Reply  `json:"code"`
	Token        string `json:"token"`
}

type UserRegiserRequest struct {
	Name       string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"confirm_password"`
}

type UserRegiserReply struct {
	ResponseData Reply `json:"responseData"`
}
